### PR TITLE
Fix interface terminal input search not checking beyond first input

### LINKED ISSUE #357: Input search only recognizes first entry
Playing on the latest CF version (the one used in Nomi dev 43a7d6b) there seems to be an issue with the input search using the interface terminal. 
Im only able to find recipes in the terminal when searching for the first input item. 
If searching for any other input, the result is empty. 

For example. In my recipe of the MV Motor, "Magnetic steel rod" is the last item in the list. If searching for "magnetic" the motor doenst show up.

### PR DESCRIPTION
**Pull request by serenibyss**
Closes #357 

Somewhat temporary fix while the searching gets more thoroughly rewritten

### CODE REVIEW

File: src/main/java/appeng/client/gui/implementations/GuiInterfaceTerminal.java [hunk 1]
```diff
@@ -584,16 +585,14 @@ private boolean itemStackMatchesSearchTerm(final ItemStack itemStack, final Stri
...
 
-                for (String term : searchTerm.split(" ")) {
+                for (String term : splitTerm) {
                     if (term.length() > 1 && (term.startsWith("-") || term.startsWith("!"))) {
                         term = term.substring(1);
                         if (displayName.contains(term)) {
                             return false;
                         }
                     } else if (displayName.contains(term)) {
                         foundMatchingItemStack = true;
```
Comment (NotMyWing) [inline src/main/java/appeng/client/gui/implementations/GuiInterfaceTerminal.java:595]: Should this not just return early?

Comment (serenibyss) [reply src/main/java/appeng/client/gui/implementations/GuiInterfaceTerminal.java:595]: We don't want to return early because a later statement could hit the negate clause, i.e. `wood !oak`

**Review by NotMyWing — APPROVED** [review]
